
CREATE TABLE `project_info` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `project_no` varchar(255) DEFAULT '' COMMENT '编号 KKC-BJ0001',
  `project_name` varchar(255) DEFAULT '' COMMENT '名称',
  `project_score` DECIMAL(20,2) DEFAULT 0 COMMENT '项目评分',
  `project_scorescale` decimal(10,2) DEFAULT 0 COMMENT '评分因子',
  `project_investstype_id` bigint DEFAULT 0 COMMENT '项目投资类型',
  `project_investstype_name` varchar(255) DEFAULT '' COMMENT '项目投资类型名称',
  `project_current_status` bigint DEFAULT 0 COMMENT '项目状态',
  `project_current_status_name` varchar(255) DEFAULT '' COMMENT '项目状态',
  `project_current_status_display` int DEFAULT 0 COMMENT '项目状态是否可见',
  `project_current_status_index` int DEFAULT 0 COMMENT '项目状态顺序',
  `project_status_start` datetime DEFAULT '1970-01-01' COMMENT '当前状态开始时间',
  `project_status_end` datetime DEFAULT '1970-01-01' COMMENT '当前状态结束时间',
  `project_scale` decimal(5,5) DEFAULT 0 COMMENT '代币权值',
  `project_coinammount` decimal(20,9) DEFAULT 0 COMMENT '代币总数量',
  `project_bonustype` bigint DEFAULT 0 COMMENT '分红类型',
  `project_bonusperiods` bigint DEFAULT 0 COMMENT '分红期数',
  `project_starttime` datetime DEFAULT '1970-01-01' COMMENT '上线时间',
  `project_holdtype` int DEFAULT 0 COMMENT '持有类型 0 个人 1 公司',
  `project_holderid` bigint DEFAULT 0 COMMENT '持有者id compony/holder',
  `project_hold_last` bigint DEFAULT 0 COMMENT '持有年限',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `deleted_at` datetime DEFAULT NULL COMMENT '删除时间',
  `created_id` bigint(20) DEFAULT NULL COMMENT '创建人',
  `updated_id` bigint(20) DEFAULT NULL COMMENT '更新人',
  `deleted_id` bigint(20) DEFAULT NULL COMMENT '删除人',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;