drop table `resource_type`; 
CREATE TABLE `resource_type` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'id',
  `resource_type_name` varchar(255) DEFAULT NULL COMMENT '类型名称',
  `resource_filetype` varchar(10) DEFAULT NULL COMMENT '文件类型',
  `resource_pre_logic` varchar(255) DEFAULT NULL COMMENT '前置处理类',
  `resource_post_logic` varchar(255) DEFAULT NULL COMMENT '后置处理类',
  `resource_model_id` bigint(20) DEFAULT NULL COMMENT '关联model id',
  `resource_model_name` varchar(255) DEFAULT NULL COMMENT '关联modelname',
  `resource_pre_param` varchar(255) DEFAULT NULL COMMENT '前置处理参数',
  `resource_post_param` varchar(255) DEFAULT NULL COMMENT '后置处理参数',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `deleted_at` datetime DEFAULT NULL,
  `created_id` bigint(20) DEFAULT NULL,
  `updated_id` bigint(20) DEFAULT NULL,
  `deleted_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
INSERT INTO `resource_type` (`id`, `resource_type_name`, `resource_filetype`, `resource_pre_logic`, `resource_post_logic`, `resource_model_id`, `resource_model_name`, `resource_pre_param`, `resource_post_param`, `created_at`, `updated_at`, `deleted_at`, `created_id`, `updated_id`, `deleted_id`)
VALUES
	(null,"图片","jpg",null,null,1,"西城房产收益权001号",null,null,NULL,NULL,null,NULL,NULL,NULL),
    (null,"图片","png",null,null,1,"西城房产收益权001号",null,null,NULL,NULL,null,NULL,NULL,NULL),
    (null,"文档","pdf",null,null,1,"西城房产收益权001号",null,null,NULL,NULL,null,NULL,NULL,NULL),
    (null,"文档","doc",null,null,1,"西城房产收益权001号",null,null,NULL,NULL,null,NULL,NULL,NULL),
    (null,"图片","jpg",null,null,2,"西城房产收益权002号",null,null,NULL,NULL,null,NULL,NULL,NULL),
    (null,"图片","png",null,null,2,"西城房产收益权002号",null,null,NULL,NULL,null,NULL,NULL,NULL),
    (null,"文档","pdf",null,null,2,"西城房产收益权002号",null,null,NULL,NULL,null,NULL,NULL,NULL),
    (null,"文档","doc",null,null,2,"西城房产收益权002号",null,null,NULL,NULL,null,NULL,NULL,NULL),
    (null,"图片","jpg",null,null,3,"西城房产收益权003号",null,null,NULL,NULL,null,NULL,NULL,NULL),
    (null,"图片","png",null,null,3,"西城房产收益权003号",null,null,NULL,NULL,null,NULL,NULL,NULL),
    (null,"文档","pdf",null,null,3,"西城房产收益权003号",null,null,NULL,NULL,null,NULL,NULL,NULL),
    (null,"文档","doc",null,null,3,"西城房产收益权003号",null,null,NULL,NULL,null,NULL,NULL,NULL),
    (null,"图片","jpg",null,null,4,"西城房产收益权004号",null,null,NULL,NULL,null,NULL,NULL,NULL),
    (null,"图片","png",null,null,4,"西城房产收益权004号",null,null,NULL,NULL,null,NULL,NULL,NULL),
    (null,"文档","pdf",null,null,4,"西城房产收益权004号",null,null,NULL,NULL,null,NULL,NULL,NULL),
    (null,"文档","doc",null,null,4,"西城房产收益权004号",null,null,NULL,NULL,null,NULL,NULL,NULL),
    (null,"图片","jpg",null,null,5,"美国房产001号",null,null,NULL,NULL,null,NULL,NULL,NULL),
    (null,"图片","png",null,null,5,"美国房产001号",null,null,NULL,NULL,null,NULL,NULL,NULL),
    (null,"文档","pdf",null,null,5,"美国房产001号",null,null,NULL,NULL,null,NULL,NULL,NULL),
    (null,"文档","doc",null,null,5,"美国房产001号",null,null,NULL,NULL,null,NULL,NULL,NULL),
    (null,"图片","jpeg",null,null,1,"西城房产收益权001号",null,null,NULL,NULL,null,NULL,NULL,NULL),
    (null,"图片","jpeg",null,null,1,"西城房产收益权002号",null,null,NULL,NULL,null,NULL,NULL,NULL),
    (null,"图片","jpeg",null,null,1,"西城房产收益权003号",null,null,NULL,NULL,null,NULL,NULL,NULL),
    (null,"图片","jpeg",null,null,1,"西城房产收益权004号",null,null,NULL,NULL,null,NULL,NULL,NULL),
    (null,"图片","jpeg",null,null,1,"美国房产001号",null,null,NULL,NULL,null,NULL,NULL,NULL);           