CREATE TABLE `lending_docinfo` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `lending_docno` varchar(30) NOT NULL DEFAULT '' COMMENT 'BLD',
  `lending_coin_type` varchar(30) NOT NULL DEFAULT '' COMMENT '代币类型',
  `lending_coin_ammount` decimal(20,9) NOT NULL DEFAULT 0 COMMENT '原始数量',
  `lending_coin_scale` decimal(20,9) NOT NULL DEFAULT 0 COMMENT '比例',
  `lending_coin_price` decimal(20,2) NOT NULL DEFAULT 0 COMMENT '价格',
  `lending_deposit` decimal(20,2) NOT NULL DEFAULT 0 COMMENT '保证金',
  `lending_lendtime` datetime NOT NULL DEFAULT '1970-01-01' COMMENT '发起时间',
  `lending_lenduser` bigint NOT NULL DEFAULT 0 COMMENT '借款人',
  `lending_scale` int NOT NULL DEFAULT 0 COMMENT '杠杆（目前1）',
  `lending_checkuser` bigint NOT NULL DEFAULT 0 COMMENT '借款审核人',
  `lending_checktime` datetime NOT NULL DEFAULT '1970-01-01' COMMENT '借款审核时间',
  `lending_type` varchar(30) NOT NULL DEFAULT '' COMMENT '种类，目前 体验标 加字典',
  `lending_status` varchar(30) NOT NULL DEFAULT '' COMMENT '状态 目前：借入申请 借入审核 还回申请 还回审核',
  `lending_plan_returntime` datetime NOT NULL DEFAULT '1970-01-01' COMMENT '计划还款时间',
  `lending_return_time` datetime NOT NULL DEFAULT '1970-01-01' COMMENT '真实还款时间',
  `lending_return_checktime` datetime NOT NULL DEFAULT '1970-01-01' COMMENT '还款审核时间',
  `lending_return_checkuser` bigint NOT NULL DEFAULT 0 COMMENT '还款审核人',
  `lending_sys_account` bigint NOT NULL DEFAULT 0 COMMENT '系统账户id',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `deleted_at` datetime DEFAULT NULL COMMENT '删除时间',
  `created_id` bigint(20) DEFAULT NULL COMMENT '创建人',
  `updated_id` bigint(20) DEFAULT NULL COMMENT '更新人',
  `deleted_id` bigint(20) DEFAULT NULL COMMENT '删除人',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;