CREATE TABLE `report_user_withdrawal_day` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `report_name` varchar(255) DEFAULT NULL COMMENT '报表名称',
  `report_no` varchar(255) DEFAULT NULL COMMENT '报表编号',
  `report_runtype` char(30) DEFAULT NULL COMMENT '报表类型',
  `report_initcount` bigint(20) DEFAULT NULL COMMENT '初始提现笔数',
  `report_withdrawalcount` bigint(20) DEFAULT NULL COMMENT '提现笔数',
  `report_resultcount` bigint(20) DEFAULT NULL COMMENT '期末提现笔数',
  `report_initinv` bigint(20) DEFAULT NULL COMMENT '初始提现人数',
  `report_withdrawalinv` bigint(20) DEFAULT NULL COMMENT '本期新增提现人数',
  `report_resultinv` bigint(20) DEFAULT NULL COMMENT '初始提现人数',
  `report_initcash` decimal(20,3) DEFAULT NULL COMMENT '初始提现金额',
  `report_withdrawalcash` decimal(20,3) DEFAULT NULL COMMENT '提现金额',
  `report_resultcash` decimal(20,3) DEFAULT NULL COMMENT '期末提现金额',
  `report_start` datetime DEFAULT NULL COMMENT '报表开始时间',
  `report_end` datetime DEFAULT NULL COMMENT '报表结束时间',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `deleted_at` datetime DEFAULT NULL COMMENT '删除时间',
  `created_id` bigint(20) DEFAULT NULL COMMENT '创建人',
  `updated_id` bigint(20) DEFAULT NULL COMMENT '更新人',
  `deleted_id` bigint(20) DEFAULT NULL COMMENT '删除人',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;