CREATE TABLE `report_user_coin_day` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `report_no` varchar(255) DEFAULT NULL COMMENT '报表编号',
  `report_name` varchar(255) DEFAULT NULL COMMENT '报表名称',
  `report_cyc` char(30) DEFAULT NULL COMMENT '报表周期',
  `report_user` bigint(20) DEFAULT NULL COMMENT '报表用户',
  `report_usermobile` char(11) DEFAULT NULL COMMENT '用户电话',
  `report_username` varchar(255) DEFAULT NULL COMMENT '用户姓名',
  `report_invuser` bigint(20) DEFAULT NULL COMMENT '邀请用户',
  `report_invcode` char(30) DEFAULT NULL COMMENT '进入的邀请码',
  `report_start` datetime DEFAULT NULL COMMENT '开始时间',
  `report_end` datetime DEFAULT NULL COMMENT '结束时间',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `deleted_at` datetime DEFAULT NULL COMMENT '删除时间',
  `created_id` bigint(20) DEFAULT NULL COMMENT '创建人',
  `updated_id` bigint(20) DEFAULT NULL COMMENT '更新人',
  `deleted_id` bigint(20) DEFAULT NULL COMMENT '删除人',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;