DROP TABLE IF EXISTS `realty_house`;

CREATE TABLE `realty_house` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `house_name` varchar(255) NOT NULL DEFAULT '' COMMENT '名称',
  `house_tradedate` date NOT NULL DEFAULT '1970-01-01' COMMENT '成交日期',
  `house_size` int NOT NULL DEFAULT 0 COMMENT '大小 以0.01为单位，即，如果为 50.06平，表示为5006',
  `house_unitprice` int NOT NULL DEFAULT 0 COMMENT '单价 以元为单位',
  `house_price` int NOT NULL DEFAULT 0 COMMENT '总价 以元为单位',
  `house_building_year` int NOT NULL DEFAULT 0 COMMENT '建设年份 1900-2100',
  `house_orientation` tinyint NOT NULL DEFAULT 0 COMMENT '朝向 0000 分别表示东南西北',
  `house_building_height` int NOT NULL DEFAULT 0 COMMENT '楼层数',
  `house_withlift` bit NOT NULL DEFAULT b'0' COMMENT '是否有电梯',
  `house_flow` varchar(255) NOT NULL DEFAULT '' COMMENT '楼层',
  `house_listprice` int NOT NULL DEFAULT 0 COMMENT '挂牌价',
  `house_transaction_cycle` int NOT NULL DEFAULT 0 COMMENT '成交周期',
  `house_building_type` varchar(255) NOT NULL DEFAULT '' COMMENT '楼型 字典表building_type BT01 板楼 BT02 塔楼 BT03 板塔结合',
  `house_district_id` bigint NOT NULL DEFAULT 0 COMMENT '小区id',
  `house_district_name` varchar(255) NOT NULL DEFAULT '' COMMENT '小区名称',
  `house_innersize` int NOT NULL DEFAULT 0 COMMENT '套内面程',
  `house_use` varchar(255) NOT NULL DEFAULT '' COMMENT '',
  `house_homelink_no` varchar(255) NOT NULL DEFAULT '' COMMENT '链家房源编号',
  `house_homeline_address` varchar(255) NOT NULL DEFAULT '' COMMENT '链家房源地址',
  `house_type_id` bigint NOT NULL DEFAULT 0 COMMENT '户型id',
  `house_type_name` varchar(255) NOT NULL DEFAULT '' COMMENT '户型名称',
  `house_subwaystation` int NOT NULL DEFAULT 0 COMMENT '附近地铁',
  `house_subwaydistance` int NOT NULL DEFAULT 0 COMMENT '距离',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `updated_at` datetime DEFAULT NULL COMMENT '更新时间',
  `deleted_at` datetime DEFAULT NULL COMMENT '删除时间',
  `created_id` bigint(20) DEFAULT NULL COMMENT '创建人',
  `updated_id` bigint(20) DEFAULT NULL COMMENT '更新人',
  `deleted_id` bigint(20) DEFAULT NULL COMMENT '删除人',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;